// =============================================================================
//                                  P A R T   I
// =============================================================================

= Spanish Language Support

In this first part of the book we'll be focusing on how the _Spanish Foundation Library_ introduces support for the Spanish language in ALAN{nbsp}3.

== The Spanish Grammar Engine

The _Spanish Foundation Library_ tries to mimic as close as possible the _English Foundation Library_ (which is the reference implementation of the Foundation Library project), except that all its classes, attributes and verbs identifiers are translated to Spanish, along with their messages.

Furthermore, the _Spanish Foundation_ includes a dedicated module for handling the Spanish grammar (`gramática.i`) which handles all the hard work of correctly setting up the gender, noun and articles of every game instance at initialization time.

Thanks to the grammar module (think of it as the "`Spanish Grammar Engine`"), authors are spared having to deal with most of the complexity of what goes on in the background of the library, allowing them to focus on writing their adventures as close to writing prose as possible.

TIP: The `gramática.i` file is designed to be a standalone module, so that it might be reused also outside of the _Spanish Foundation Library_, e.g. to build your own Spanish library, or a Spanish adventure from scratch, without using the other modules of the _Foundation Library_.


== How to Define the Gender and Number of Game Instances

When creating game entities (i.e. _things_: actors and objects) in your adventure, in order to define their gender and number all you need to need to do is to inform the library what article is associated with their instances.
By default, all instances of the base classes are considered masculine singular with article "`el`", so you don't need to specify anything for instances which are masculine in gender, singular in number, and take "`el`" as their article.
In all other cases, you'll have to specify the article via the `artículo` string-attribute, e.g.:

[source,alan]
Has artículo "la".

Before the game starts, the library will use that information to deduce how to initialize every game instance correctly, by setting its indefinite article and all other gender and number references accordingly.

[source,alan]
------------------------------
include::_gna1.alan[tags=basic;!*]
------------------------------

<1> This line imports the _Spanish Foundation Library_ into the game.
<2> Since _árbol_ is m.s. we don't need to specify the "`el`" article.

As shown by the transcript below, all library messages contain correct gender and number references to the objects created above:

[example,role="gametranscript"]
====================================
include::_gna1.a3t-adoc[lines=3..13]
====================================

It's worth noting at this point that definite articles are stripped away from the player's input, because they don't provide meaningful information to the game parser.
Hence, for the parser the above commands are identical to the following ones:

[example,role="gametranscript"]
=============================================
include::_gna1.a3t-adoc[tag=basic-no-article]
=============================================

Moreover, any definite article in the player input will work just fine, regardless of whether it matches the gender and number of the noun:

[example,role="gametranscript"]
==============================================
include::_gna1.a3t-adoc[tag=basic-any-article]
==============================================

Therefore, defining the gender and number of game instances is only relevant to outgoing messages (i.e. generated by the library or the game), not to handling player input.

WARNING: The above statement might only be partially true, because when it comes to `PRONOUNS` gender and number might affect player input.
So we need to revisit this topic once the `gramática.i` module is completed, and test how references other than determinate articles might affect player input parsing.


=== Feminine Nouns with Masculine Article

In Spanish there are certain feminine nouns that take masculine articles in their singular form, e.g. "`el agua`" and "`una agua`" instead of "`la agua`" and "`un agua`".
These nouns are feminine in all respects from the grammar point of view, so they need to be treated accordingly when it comes to adjectives, etc.

The _Spanish Foundation Library_ provides authors with a simple way to handle these nouns, by simply specifying `is femenina`, without the `artículo`.
The grammar module will check at initialization time for objects which have both the `artículo "el"` (the default) and `is femenina` attributes, and treat them accordingly.

[source,alan]
----------------------------------
include::_gna1.alan[tags=hacha;!*]
----------------------------------

NOTE: Although these nouns can correctly take either the masculine or feminine indefinite article, the library opts for the former since it's more common and consistent with the determinative article.

[example,role="gametranscript"]
========================================
include::_gna1.a3t-adoc[tag=fs-el-basic]
========================================

WARNING: The library currently doesn't handle correctly "`de el`", which should have been contracted into "`del`" in the above library response.
When the problem is fixed at the library level, the documentation examples will automatically be fixed too.

When these special feminine nouns are preceded by an adjective (or any other word between the noun and its article) they require taking the "`LA`" article, instead of "`EL`".

In these cases, authors needs to treat the adjective and noun as if they were a single compound word, via the `Mentioned` clause, and specify the  `artículo "la"` attribute in the object definition.
Although players can freely refer to the noun with and without adjective, and using any article, the adventure needs to compromise on a single way to address the noun in a consistent fashion in all its messages -- i.e. it can't mention just the noun (using the "`EL`"/"`UN`" articles) in some places, and the noun preceded by its adjective  (using "`LA`"/"`UNA`") elsewhere, because each instance can hold just single gender and number definition.

[source,alan]
---------------------------------
include::_gna1.alan[tags=arpa;!*]
---------------------------------

<1> Thanks to the `mentioned` clause we can treat the noun and its adjective as a compound word, ensuring that they're mentioned together whenever the object is referenced in library, game and runtime messages.
<2> In `name` clauses with two words, the first one is always treated as the adjective and the second as the noun; therefore players can always refer to the object in its full form (adjective + noun) or just by the noun, but never by the adjective alone.
<3> The alternative `name` clause with "`pequeña`" mispelled as "`pequena`" is provided for players using non-Spanish keyboards, where the kbd:[Ñ] key is not available.
<4> Of course, in custom messages that don't rely on parameters references, authors are free to mention the noun as they please, with or without the preceding adjective, and using the correct article accordingly.

[example,role="gametranscript"]
==============================================
include::_gna1.a3t-adoc[tag=fs-el-adj]
==============================================

////

////
