// =============================================================================
//                                 P A R T   I I
// =============================================================================

= Design Principles

During the process of updating the old ALAN Library v0.6 to the new ALAN Foundation Library we decided to set some goals regarding the scope of the library, its target audience, and its design principles.

This document is our attempt to lay down those principles in order to allow adventures authors to better understand the underlying library structure, so that they may extend the library following the same principles.

== Implicit Taking

Well polished text adventures usually implement implicit taking action for some verbs, so that the player doesn't have to first take the item to complete that action.

By design, we chose not to implement implicit taking in any of the library defined verbs, leaving it to end author to decide which verbs deserve this feature, and how to implement it.
